attendance/urls.py
from django.urls import path
from . import views

app_name = 'attendance'

urlpatterns = [
    path('', views.home, name='home'),
    path('register_attendance/', views.register_attendance, name='register_attendance'),
    path('time-in/', views.time_in, name='time_in'),
    path('time-out/', views.time_out, name='time_out'),
    path('attendance-record/', views.attendance_record, name='attendance_record'),
    
]

employee/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_employee, name='list_employee'),
    path('edit_employee/<int:pk>/', views.edit_employee, name='edit_employee'),
    path('create_employee', views.create_employee, name='create_employee'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]	

farmsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('attendance.urls', 'attendance'), namespace='home')),
    path('employee/', include(('employee.urls', 'employee'), namespace='employee')),
    path('attendance/', include(('attendance.urls', 'attendance'), namespace='attendance')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('item/', include(('item.urls', 'item'), namespace='item')),
    #path('sale/', include(('sale.urls', 'sale'), namespace='sale')),
    #path('expense/', include(('expense.urls', 'expense'), namespace='expense')),
    #path('order/', include(('order.urls', 'order'), namespace='order')),
    #path('cashflow/', include(('cashflow.urls', 'cashflow'), namespace='cashflow'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employee/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
#from django.utils import timezone



class EmployeeUser(AbstractUser):
    
    firstname = models.CharField(max_length=24)
    lastname = models.CharField(max_length=24)
    birth_date = models.DateField(blank=True, null=True)
    manager = models.BooleanField(blank=True, default=False, null=True)


    def __str__(self):
        return self.username + ' - ' + self.firstname + ' ' + self.lastname

employee/forms.py
import datetime
from django import forms
from .models import EmployeeUser #, PayrollEmployee, Payroll
from django.forms import formset_factory

class EmployeeUserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
       super(EmployeeUserForm, self).__init__(*args, **kwargs)
       fields = [
                'username'
                'firstname',
                'lastname',
                'password', 
                'birth_date',
                'is_active'
                'manager']

    class Meta:
        model = EmployeeUser
        fields = [
                'username',
                'password',
                'firstname',
                'lastname', 
                'birth_date',
                'is_active',
                'manager']
        widgets = {
                'password': forms.PasswordInput(),
                'manager': forms.CheckboxInput(),
            }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.is_superuser = False
        if commit:
            user.save()
        return user

"""
class PayrollForm(forms.ModelForm):
    class Meta:
        model = Payroll
        exclude = []

    payroll_sched = forms.ChoiceField(choices=Employee.payroll_sched_choices)
    date = forms.DateField(initial=datetime.date.today(),
                          widget=forms.widgets.DateInput(format="%m/%d/%Y"))

   
    def clean(self):
        data = super().clean()
        schedule = data.get('payroll_sched')
        date = data.get('date')
        if schedule == 'w':
            if date.strftime('%w') != '6':
                raise forms.ValidationError("Weekly Payroll is only on Saturday!")
        elif schedule == 'm':
            if date.strftime('%d') not in [15, 30, 31]:
                raise forms.ValidationError("Monthly Payroll is only on the 15th and 30th/31st!")
        elif schedule == 'c':
            if date.strftime('%w') != '6':
                raise forms.ValidationError("Construction Payroll is only on Saturday!")
        return data
        

class PayrollEmployeeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PayrollEmployeeForm, self).__init__(*args, **kwargs)
        fields = [
              'employee',
              'absent', 
              'deduction',
              ]

    class Meta:
        model = PayrollEmployee
        exclude = ['payroll']

payrollemployeeformset = formset_factory(PayrollEmployeeForm, extra=0)
"""

employee/views.py
import datetime
from django.shortcuts import render, get_object_or_404, redirect
from .models import EmployeeUser #, Payroll, PayrollEmployee, EmployeeCashAdvance
from .forms import EmployeeUserForm #PayrollForm, payrollemployeeformset

from django.http import HttpResponse
from django.db.models import Sum
#from django.template.loader import render_to_string
#from weasyprint.fonts import FontConfiguration
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
#from weasyprint import HTML
from django.contrib.auth.decorators import login_not_required

def list_employee(request):
    employees = EmployeeUser.objects.filter(is_active=True).order_by('lastname')
    args = {'employees': employees }
    return render(request, 'employee/list_employee.html', args)

def edit_employee(request, pk):
    context = {}
    employee = get_object_or_404(EmployeeUser, pk=pk)
    if request.method == 'GET':
        form = EmployeeUserForm(instance=employee)
    else:
        form = EmployeeUserForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save()
            return redirect('employee:list_employee')
    context = {'form': form, 'employee':employee}
    return render(request, 'employee/edit_employee.html', context)

def create_employee(request):
    context = {}
    if request.method == 'POST':
        form = EmployeeUserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            name = instance.firstname + ' ' + instance.lastname
            context.update({'message': name + ' saved.'})
    else:
        form = EmployeeUserForm()
    context.update({'form':form})
    return render(request, 'employee/edit_employee.html', context)

@login_not_required
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('attendance:register_attendance')
        else:
            messages.error(request, 'Invalid username or password.')

    return render(request, 'registration/login.html')

def logout_view(request):
    logout(request)
    return redirect('employee:login')

"""def payroll(request):
    context = {'title':'Payroll'}
    if request.method == 'POST':
        form = PayrollForm(request.POST)
        if form.is_valid():
            sched = form.cleaned_data.get('payroll_sched')
            request.session['payroll_sched'] = sched
            employees = Employee.objects.filter(payroll_sched=sched,
                                        active=True).order_by('lastname')
            data = []
            for e in employees:
                data.append({'employee':e})
            payrollemployeeform = payrollemployeeformset(initial=data)
            context.update({'payrollemployeeform': payrollemployeeform})
            context.update({'payroll_sched': sched})
    else:
        form = PayrollForm()
    context.update({'form': form})
    return render(request, 'employee/payroll.html', context) 

def create_payroll(request):
    context = {'title':'Payroll Created'}
    if request.method == 'POST':
        payrollemployeeform = payrollemployeeformset(request.POST)
        if payrollemployeeform.is_valid():
            sched = request.session.get('payroll_sched')
            payroll = Payroll(date=datetime.date.today(),
                                        payroll_sched=sched)
            payroll.save()
            for pe_form in payrollemployeeform:
                i = pe_form.save(commit=False)
                i.payroll = payroll
                i.save()
            del request.session['payroll_sched']
        payrollemployees = PayrollEmployee.objects.filter(payroll=payroll)
        context.update({'employees':payrollemployees})
        context.update({'payroll': payroll})

    return redirect('employee:list_payroll')

def list_payroll(request):
    context = {'title' : 'Payroll List'}
    payroll = Payroll.objects.all().order_by('-date')
    context.update({'payroll': payroll})
    return render(request, 'employee/list_payroll.html', context)

def list_payroll_employees(request, pk):
    payroll = Payroll.objects.get(id=pk)
    d = payroll.date
    payroll_date = d.strftime("%m/%d/%Y")
    payroll_sched = payroll.get_payroll_sched_display()
    title = 'Employees in Payroll Date: ' + payroll_date + ' (' + payroll_sched + ')'
    context = {'title' : title }
    employees = PayrollEmployee.objects.filter(payroll=payroll)
    total = 0
    for e in employees:
        e.total_days = (6 - e.absent) + e.overtime
        e.gross = round(e.employee.rate * e.total_days)
        e.net = e.gross - e.deduction
        total += e.net
    context.update({'payroll': payroll})
    context.update({'total':total})
    context.update({'payroll_employees': employees})
    return render(request, 'employee/list_payroll_employees.html', context)

def print_payroll_employee(request, payroll_pk):
    payroll = get_object_or_404(Payroll, pk=payroll_pk)
    payroll_employees = PayrollEmployee.objects.select_related('employee'
                                        ).filter(payroll=payroll).order_by('employee__lastname')
    for e in payroll_employees:
        e.total_days = (6 - e.absent) + e.overtime
        e.gross = round(e.employee.rate * e.total_days)
        e.net = e.gross - e.deduction
    context = {'employees' : payroll_employees}
    context.update({'payroll': payroll})
    
    html_string = render_to_string('employee/print_payroll_employee.html', context)
    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = 'inline; filename=print_payroll.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    font_config = FontConfiguration()
    HTML(string=html_string).write_pdf(response, font_config=font_config)
    return response
"""

employee/templates/employee/core_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Attendance System</title>
		<!-- Custom fonts for this template-->
	  <link href="{% static 'startbootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
	  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

	          <!-- Custom styles for this template-->
	  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
     <link href="{% static 'css/custom_css.css' %}" rel="stylesheet">

        {% block head_extra %} {% endblock %}
    
	</head>
	<body id="page-top">
{% block core_extra %} {% endblock %}
        
       
		<!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Ate Ana's Website </div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'attendance:register_attendance' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
     <hr class="sidebar-divider">


      <!-- Nav Item - Pages Collapse Menu -->
    {% if request.user.manager %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEmployee" aria-expanded="true" aria-controls="collapseEmployee">
          <i class="fas fa-fw fa-address-book"></i>
          <span>Employees</span>
        </a>
        <div id="collapseEmployee" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
          <!--<h6 class="collapse-header">Custom Components:</h6>-->
            <a class="collapse-item" href="{% url 'employee:list_employee' %}">List Employees</a>
            <a class="collapse-item" href="{% url 'employee:create_employee' %}">Add Employee </a>
          </div>
        </div>
      </li>
    {% endif %}

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-address-book"></i>
          <span>Attendance</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
          <!--<h6 class="collapse-header">Custom Components:</h6>-->
            <a class="collapse-item" href="{% url 'attendance:register_attendance' %}" >Register Attendance</a>
              {% if request.user.manager %}
            <a class="collapse-item" href="{% url 'attendance:attendance_record' %}">Attendance Records</a>
              {% endif %}
          </div>
        </div>
      </li>
    
   <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-address-book"></i>
          <span>Attendance</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" >Register Attendance</a>
            <a class="collapse-item" >List Attendance</a>
          </div>
        </div>
      </li> -->

    

     




      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->
     <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                
            <div class="nav-link mr-2 d-none d-lg-inline">
                    
            <form action="{% url 'employee:logout' %}" method="post">
                {% csrf_token %}
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                <input style='border:none;background-color:transparent;' class='text-gray-600 small' type="submit" value='Logout'>
            </form>
            </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
            <h3>{{ title }}</h3>
            <h5 style='color:lightslategray'>{{ message }}</h5>
              {% block content %}
              {% endblock %}
         
        </div>
      <!-- End of Main Content -->

      <!-- Footer 
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer> -->
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>


</div>
  <!-- Modal -->
        
        <div id="modal-div"></div>



 <!-- Bootstrap core JavaScript-->
  <script src="{% static 'startbootstrap/vendor/jquery/jquery.min.js' %}" type='text/javascript'>
  </script>

  <script type='text/javascript' src="{% static 'startbootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script type='text/javascript' src="{% static 'startbootstrap/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'startbootstrap/js/sb-admin-2.min.js' %}"></script>



  <!-- Page level plugins -->
 <!-- <script src="{% static 'startbootstrap/vendor/chart.js/Chart.min.js' %}"></script>-->

  <!-- Page level custom scripts -->
 <!-- <script src="{% static 'startbootstrap/js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'startbootstrap/js/demo/chart-pie-demo.js' %}"></script> -->
    {% block javascript %}
    {% endblock %}


<!-- open modal -->
<script type='text/javascript'>
var modalDiv = $("#modal-div");

$(".open-modal").on("click", function() {
  $.ajax({
    url: $(this).attr("data-href"),
    success: function(data) {
      modalDiv.html(data);
      $("#myModal").modal();
    }
  });
});
</script>
<!-- end open modal -->

	</body>
</html>

employee/templates/employee/edit_employee.html
{% extends "employee/core_template.html" %}
{% load static %}

{% block content %}
	

<div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Employee Info</h6>

                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                    <form method="post">
                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}

                        {% for error in field.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>



                </div>
            </div>

</div>




{% endblock %}

employee/templates/employee/list_employee.html
{% extends "employee/core_template.html" %}
{% load static %}

{% block content %}

<div class="row">

        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Employee List</h6>

                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                        <table style='border: 1px solid;width:100%'>
                            <thead ><tr>
                            <th style='border: 1px solid;'>#</th>
                            <th style='border: 1px solid;'>Name </th>
                            </tr> </thead>
                  {% for e in employees %}
                    <tr style='border: 1px solid; '>
                        <td style='border: 1px solid;padding:3px;'>{{ forloop.counter }}</td>
                         <td style='border: 1px solid;'><a href="{% url 'employee:edit_employee' pk=e.pk %}"> {{e}} </a> </td>
                    </tr>

                {% empty %}
                    <li>No records yet.</li>
                {% endfor %}
                </table>


                </div>
            </div>
        </div>

    </div>








{% endblock %}